Submit jobs in blocks. Uses default queue only.

diff --git a/src/sgeutils/fsl_sub b/src/sgeutils/fsl_sub
--- a/src/sgeutils/fsl_sub
+++ b/src/sgeutils/fsl_sub
@@ -89,14 +89,14 @@
 # cluster to be used.
 ###########################################################################
 
-METHOD=SGE
+METHOD=PBS
 if [ "x$SGE_ROOT" = "x" ] ; then
     if [ -f /usr/local/share/sge/default/common/settings.sh ] ; then
 	. /usr/local/share/sge/default/common/settings.sh
     elif [ -f /usr/local/sge/default/common/settings.sh ] ; then
 	. /usr/local/sge/default/common/settings.sh
     else
-	METHOD=NONE
+	METHOD=PBS
     fi
 fi
 
@@ -113,14 +113,15 @@ fi
 
 map_qname ()
 {
-    if [ $1 -le 20 ] ; then
-	queue=veryshort.q
-    elif [ $1 -le 120 ] ; then
-	queue=short.q
-    elif [ $1 -le 1440 ] ; then
-	queue=long.q
+    if [ $1 -le 60 ] ; then
+	queue=default
+	ppn=8
+    elif [ $1 -le 8864 ] ; then
+	queue=default
+	ppn=8
     else
-	queue=verylong.q
+	queue=default
+	ppn=8
     fi
     #echo "Estimated time was $1 mins: queue name is $queue"
 }
@@ -140,16 +141,16 @@ usage ()
 
 $command V1.0beta - wrapper for job control system such as SGE
 
-Usage: $command [options] <command>
+Usage: fsl_sub [options] <command>
 
 $command gzip *.img *.hdr
-$command -q short.q gzip *.img *.hdr
+$command -q default gzip *.img *.hdr
 $command -a darwin regscript rawdata outputdir ...
 
   -T <minutes>          Estimated job length in minutes, used to auto-set queue name
-  -q <queuename>        Possible values for <queuename> are "verylong.q", "long.q" 
-                        and "short.q". See below for details
-                        Default is "long.q".
+  -q <queuename>        Possible values for <queuename> are "default", "default" 
+                        and "default". See below for details
+                        Default is "default".
   -a <arch-name>        Architecture [e.g., darwin or lx24-amd64]
   -p <job-priority>     Lower priority [0:-1024] default = 0                 
   -M <email-address>    Who to email, default = `whoami`@fmrib.ox.ac.uk 
@@ -163,17 +164,16 @@ $command -a darwin regscript rawdata outputdir ...
 
 Queues:
 
-There are several batch queues configured on the cluster, each with defined CPU
-time limits. All queues, except bigmem.q, have a 8GB memory limit.
+There are three batch queues configured on the cluster, each with defined CPU
+time limits.
 
-veryshort.q:This queue is for jobs which last under 30mins.
-short.q:    This queue is for jobs which last up to 4h. 
-long.q:     This queue is for jobs which last less than 24h. Jobs run with a
-            nice value of 10.
-verylong.q: This queue is for jobs which will take longer than 24h CPU time.
+default:This queue is for jobs which last under 30mins.
+default:    This queue is for jobs which last up to 2h. 
+default:     This queue is for jobs which last less than 24h.
+default: This queue is for jobs which will take longer than 24h CPU time.
             There is one slot per node, and jobs on this queue have a nice value
-            of 15.
-bigmem.q:   This queue is like the verylong.q but has no memory limits.
+            of 5. If jobs enter the default queue then items running on this
+            queue are suspended and resumed on completion of the default task.
 
 EOF
 
@@ -185,7 +185,7 @@ if [ $nargs -eq 0 ] ; then
   usage
 fi
 
-set -- `getopt T:q:a:p:M:j:t:N:Fvm:l: $*`
+set -- `getopt T:q:a:p:M:j:k:t:N:Fvm:l: $*`
 result=$?
 if [ $result != 0 ] ; then
   echo "What? Your arguments make no sense!"
@@ -201,9 +201,11 @@ fi
 # change. It also sets up the basic emailing control.
 ###########################################################################
 
-queue=long.q
-mailto=`whoami`@fmrib.ox.ac.uk
-MailOpts="n"
+queue=default
+ppn=8
+mailto=`whoami`@`hostname`
+MailOpts="ae"
+nodes="-l nodes=1 -l pmem=256mb"
 
 
 ###########################################################################
@@ -249,20 +251,7 @@ while [ $1 != -- ] ; do
       queue=$2
       shift;;
     -a)
-      acceptable_arch=no
-      available_archs=`qhost | tail -n +4 | awk '{print $2}' | sort | uniq`
-      for a in $available_archs; do
-	if [ $2 = $a ] ; then
-	  acceptable_arch=yes
-	fi
-      done
-      if [ $acceptable_arch = yes ]; then
-	  sge_arch="-l arch=$2"
-      else
-	  echo "Sorry arch of $2 is not supported on this SGE configuration!"
-	  echo "Should be one of:" $available_archs
-	  exit 127
-      fi
+      sge_arch="-l arch=$2"
       shift;;
     -p)
       sge_priority="-p $2"
@@ -271,13 +260,68 @@ while [ $1 != -- ] ; do
       mailto=$2
       shift;;
     -j)
-      jid=$2
+      # to shorten dependencies, remove hostnames
+      jid=`echo $2 | sed 's/,/\n/g' | sed s/\..*//g`
+
+        for arg in `echo $jid`
+        do #checkjob $arg > /dev/null
+                if [ $? = 0 ]
+                then
+                        holds=$holds:$arg
+                else
+                        holds=$holds:$arg
+                fi
+
+        done
+
+        holds=`echo $holds | sed s/^://g`
       sge_hold="-hold_jid $jid"
+      pbs_hold="-W depend=afterany:$holds"
+      shift;;
+    -k)
+      #jid=$2
+      dependjid=${2%%@*}
+      dependon=${2#*@}
+      jid=`echo $dependjid | sed 's/,/\n/g' | sed s/\..*//g`
+
+	#echo jid : $jid >&2
+
+	for arg in `echo $jid`
+	do #checkjob $arg > /dev/null
+		if [ $? = 0 ]
+		then
+			holds=$holds:$arg
+		else
+			holds=$holds:$arg
+			#count=1
+			#echo "Either it is an arry or the job doesn't exist. Expanding the array" >&2
+			#while checkjob $arg-$count > /dev/null
+			#do
+			#
+			#	holds=$holds:$arg-$count
+			#	((count=$count+1))
+			#done
+		fi
+
+	done
+
+	holds=`echo $holds | sed s/^://g`
+	#echo holds: $holds >&2
+
+
+      sge_hold="-hold_jid $jid"
+      pbs_hold="-W depend=beforeany:$holds,on:$dependon"
+#echo $pbs_hold >&2
       shift;;
     -t)
       taskfile=$2
-      tasks=`wc -l $taskfile | awk '{print $1}'`
+      #tasks=`wc -l $taskfile | awk '{print $1}'`
+      tasks=`grep -v '^#' $taskfile | sed '/^$/d' | wc -l | awk '{print $1}'`
       sge_tasks="-t 1-$tasks"
+      #pbs_tasks=$( perl -e "use Math::Libm qw(:all);  print ceil($tasks / $ppn)" )
+      #pbs_tasks="-t $pbs_tasks"
+      pbs_tasks="-t 1-$tasks"
+      nodes="-l nodes=$tasks"
       shift;;
     -N)
       JobName=$2;
@@ -286,7 +330,8 @@ while [ $1 != -- ] ; do
       MailOpts=$2;
       shift;;
     -l)
-      LogOpts="-o $2 -e $2";
+      #LogOpts="-o $2 -e $2";
+      LogOpts="-o $2/$2.out -e $2/$2.err";
       LogDir="${2}/";
       mkdir -p $2;
       shift;;
@@ -317,6 +362,7 @@ if [ "x$tasks" != x ] && [ ! -f "$taskfile" ] ; then
     echo $taskfile: invalid input!
     echo Should be a text file listing all the commands to run!
     exit -1
+
 fi
 
 if [ "x$tasks" != "x" ] && [ "x$@" != "x" ] ; then
@@ -364,6 +410,77 @@ EOF
 	fi
 	;;
 
+    PBS)
+echo "PBS: $@" >&2
+	if [ "x$tasks" = "x" ] ; then
+	    if [ $scriptmode -ne 1 ] ; then
+		#echo "Sorry can't do this when using PBS. Exiting."
+		echo "Not in Script Mode" >&2 # [DiN]
+		TEMP=`mktemp`
+		echo $@ > $TEMP
+		pbs_command="qsub $nodes -V  -d $( pwd ) -q $queue -M $mailto -N $JobName -m $MailOpts $LogOpts $pbs_hold $TEMP" 
+		# FOR DIAGNOSIS
+		echo pbs_command: $pbs_command >&2
+		echo CWD: $CWD >&2
+		echo PWD: $PWD >&2
+		echo TEMP:  $TEMP >&2
+		if [ $verbose -eq 1 ] ; then 
+		    echo pbs_command: $pbs_command >&2
+		    echo control file: $taskfile >&2
+		fi
+#	    fi	
+#		exit 1
+	    else
+		pbs_command="qsub $nodes -V  -d $( pwd ) -q $queue -M $mailto -N $JobName -m $MailOpts $LogOpts $pbs_hold $@"
+		TEMP=`mktemp`
+		echo $@ > $TEMP
+		if [ $verbose -eq 1 ] ; then 
+		    echo pbs_command: $pbs_command >&2
+		    echo control file: $taskfile >&2
+		fi
+	    fi
+	    #exec $pbs_command $@
+	    exec $pbs_command 
+	else
+	    pbs_command="qsub $nodes  -V -d $( pwd ) -q $queue -N $JobName  $LogOpts $pbs_hold $pbs_tasks"
+#	    pbs_command="qsub $nodes  -V -d $( pwd ) -q $queue -M $mailto -N $JobName -m $MailOpts $LogOpts $pbs_hold $pbs_tasks"
+		# FOR DIAGNOSIS
+		echo "IN SCRIPT ARRAY MODE"
+		echo pbs_command: $pbs_command >&2
+		echo CWD: $CWD
+		echo PWD: $PWD
+		echo TEMP:  $TEMP
+	    if [ $verbose -eq 1 ] ; then 
+		echo method: $METHOD <&2
+		echo pbs_command: $pbs_command >&2
+		echo control file: $taskfile >&2
+	    fi
+
+#	    cat <<EOF
+	    exec $pbs_command <<EOF
+
+#!/bin/sh
+
+#$ -S /bin/sh
+
+# job ids start from 0 to array_size - 1, but sed only likes line numbers from 1 up
+let i=${PBS_ARRAYID}+1
+
+#command=\`sed -n -e "\${i}p" $taskfile\`
+#command=\`$FSL_DIR/bin/chunk.pl \${PBS_ARRAYID}  $taskfile\`
+#command=\`cat $taskfile | head -\${PBS_ARRAYID}  | tail -1\`
+command=\`sed -n ${PBS_ARRAYID}p $taskfile \`
+
+echo "/bin/sh -c \"\$command\""
+echo executing jobs
+eval /bin/sh -c "\$command"
+echo waiting for jobs
+wait
+echo done waiting for jobs
+EOF
+	fi	
+	;;
+
 ###########################################################################
 # Don't change the following - this runs the commands directly if a
 # cluster is not being used.
@@ -403,4 +520,5 @@ esac
 ###########################################################################
 # Done.
 ###########################################################################
+
 
